In [1]:
import numpy as np

Ques 1

In [2]:
arr = np.arange(0,6)

In [3]:
arr

array([0, 1, 2, 3, 4, 5])

In [4]:
arr.dtype

dtype('int64')

Ques 2

In [5]:
arr = np.array([1.5, 2.6, 3.7])

In [6]:
arr.dtype

dtype('float64')

Ques 3

In [7]:
arr = np.array([1 + 2j, 3 - 4j, 5 + 6j])

In [8]:
arr

array([1.+2.j, 3.-4.j, 5.+6.j])

In [9]:
arr.dtype

dtype('complex128')

Ques4

In [10]:
arr = np.arange(0,6)

In [11]:
arr1 = arr.astype(np.float32)

In [12]:
arr1

array([0., 1., 2., 3., 4., 5.], dtype=float32)

Ques 5

In [13]:
arr = np.array([1.5, 2.6, 3.7])

In [14]:
arr.dtype

dtype('float64')

In [15]:
arr2 = arr.astype(np.float32)

In [16]:
arr2

array([1.5, 2.6, 3.7], dtype=float32)

Ques 6

In [17]:
def array_dimensions(arr):
    return arr.dtype,arr.shape , arr.size

In [18]:
array_dimensions(arr)

(dtype('float64'), (3,), 3)

Ques 7

In [19]:
def array_dimension(arr):
    return arr.ndim

In [20]:
array_dimension(arr)

1

Ques8

In [21]:
def item_size_info(arr):
    return arr.size,arr.nbytes

In [22]:
item_size_info(arr)

(3, 24)

Ques 9

In [23]:
def array_strides(arr):
    return arr.strides

In [24]:
array_strides(arr)

(8,)

Ques 10

In [25]:
def shape_strides_relationship(arr):
    return arr.shape,arr.strides

In [26]:
shape_strides_relationship(arr)

((3,), (8,))

Ques 11

In [27]:
def array(x):
    return np.zeros(x)

In [28]:
arr = array(5)

In [29]:
arr

array([0., 0., 0., 0., 0.])

Ques 12

In [30]:
def ones_array(x,y):
    return np.ones((x,y))

In [31]:
arr = ones_array(3,4)

In [32]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Ques 13

In [33]:
def generate_range_array(x,y,z):
    return np.arange(x,y,z)

In [34]:
arr = generate_range_array(1,10,2)

In [35]:
arr

array([1, 3, 5, 7, 9])

Ques 14

In [36]:
def generate_linear_space(x,y,z):
    return np.linspace(x,y,z)

In [37]:
arr = generate_linear_space(2.5,6.5,20)

In [38]:
arr

array([2.5       , 2.71052632, 2.92105263, 3.13157895, 3.34210526,
       3.55263158, 3.76315789, 3.97368421, 4.18421053, 4.39473684,
       4.60526316, 4.81578947, 5.02631579, 5.23684211, 5.44736842,
       5.65789474, 5.86842105, 6.07894737, 6.28947368, 6.5       ])

Ques 15

In [39]:
def create_identity_matrix(x):
    return np.eye(x)

In [40]:
arr = create_identity_matrix(5)

In [41]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Ques 16

In [42]:
l =[1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

Ques 17

In [43]:
arr = np.random.randint(1,9,(4,6))

In [44]:
arr

array([[6, 4, 8, 7, 3, 1],
       [4, 7, 4, 3, 2, 3],
       [4, 3, 8, 3, 7, 4],
       [4, 7, 6, 8, 5, 8]], dtype=int32)

In [45]:
arr1 = arr.view().reshape(8,3)

In [46]:
arr1

array([[6, 4, 8],
       [7, 3, 1],
       [4, 7, 4],
       [3, 2, 3],
       [4, 3, 8],
       [3, 7, 4],
       [4, 7, 6],
       [8, 5, 8]], dtype=int32)

Ques 18

In [47]:
arr1 = np.random.randint(1,9,(3,3))
arr2 = np.random.randint(1,9,(3,3))

In [48]:
arr1,arr2

(array([[3, 7, 8],
        [5, 5, 5],
        [6, 7, 2]], dtype=int32),
 array([[3, 1, 4],
        [2, 7, 8],
        [3, 4, 1]], dtype=int32))

In [49]:
arr3 = np.concatenate((arr1,arr2),axis =1)

In [50]:
arr3

array([[3, 7, 8, 3, 1, 4],
       [5, 5, 5, 2, 7, 8],
       [6, 7, 2, 3, 4, 1]], dtype=int32)

Ques19

In [51]:
arr1 = np.random.randint(1,9,(2,4))

In [52]:
arr2 = np.random.randint(1,9,(3,4))

In [53]:
arr1,arr2

(array([[2, 3, 5, 5],
        [1, 4, 3, 7]], dtype=int32),
 array([[2, 2, 4, 3],
        [4, 3, 2, 4],
        [4, 5, 1, 6]], dtype=int32))

In [54]:
arr3 = np.concatenate((arr1,arr2),axis=0)

In [55]:
arr3

array([[2, 3, 5, 5],
       [1, 4, 3, 7],
       [2, 2, 4, 3],
       [4, 3, 2, 4],
       [4, 5, 1, 6]], dtype=int32)

Ques 20

In [56]:
def stack_arrays_vertically(arr_list):
    return np.vstack(arr_list)

In [57]:
arr1 = np.random.randint(1,9,(2,4))
arr2 = np.random.randint(1,9,(2,4))
arr3 = np.random.randint(1,9,(2,4))
arr4 = np.random.randint(1,9,(2,4))


In [58]:
arr5 = stack_arrays_vertically([arr1,arr2,arr3,arr4])

In [59]:
arr5

array([[3, 4, 2, 6],
       [1, 8, 2, 3],
       [3, 5, 2, 4],
       [3, 4, 3, 2],
       [3, 8, 6, 7],
       [4, 3, 5, 8],
       [7, 2, 8, 2],
       [6, 6, 7, 4]], dtype=int32)

QUES 21

In [60]:
arr1 = np.random.randint(1,9,(2,4))
arr1

array([[4, 5, 7, 1],
       [8, 2, 3, 1]], dtype=int32)

Ques 22

In [61]:
arr5 = np.linspace(0,1,10)
arr5

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Ques23

In [62]:
arr5 = np.logspace(np.log10(1),np.log10(1000),5)
arr5

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

Ques 24

In [63]:
import pandas as pd
random_array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])

print("Random DataFrame:")
print(df)

Random DataFrame:
   Column1  Column2  Column3
0        7       21       19
1       62       98       18
2       70       14       53
3       76       84       73
4       94       71       22


Ques 25

In [64]:
import pandas as pd
import numpy as np

def replace_negatives_with_zeros(df, column_name):
    if column_name not in df.columns:
        raise ValueError(f"Column '{column_name}' does not exist in the DataFrame.")

    df[column_name] = np.maximum(df[column_name], 0)

    return df

data = {'A': [1, -2, 3, -4, 5], 'B': [10, 20, -30, 40, -50]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df_modified = replace_negatives_with_zeros(df, 'A')

print("\nModified DataFrame:")
print(df_modified)


Original DataFrame:
   A   B
0  1  10
1 -2  20
2  3 -30
3 -4  40
4  5 -50

Modified DataFrame:
   A   B
0  1  10
1  0  20
2  3 -30
3  0  40
4  5 -50


Ques 26

In [65]:
arr = np.array([10, 20, 30, 40, 50])

In [66]:
arr[2]

np.int64(30)

Ques 27

In [67]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


In [68]:
arr_2d[1,2]

np.int64(6)

Ques 28

In [69]:
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr>5]

array([ 8, 10,  7])

Ques 29

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

Ques 30

In [71]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

Ques 31

In [72]:
def extract_elements(x,y,z,w,arr):
    return arr[x:y+1,z:w+1]
extract_elements(0,1,1,2,arr_2d)

array([[2, 3],
       [5, 6]])

In [73]:
#Ques 32

In [74]:
def filter_elements(arr,x):
    return arr[arr>x]
filter_elements(arr_2d,4)

array([5, 6, 7, 8, 9])

Ques 33

In [75]:
import numpy as np

def extract_elements_3d(arr, indices_dim1, indices_dim2, indices_dim3):
    extracted_elements = arr[indices_dim1, indices_dim2, indices_dim3]
    return extracted_elements

arr_3d = np.random.randint(1, 100, size=(3, 4, 5))
indices_dim1 = np.array([0, 1, 2])
indices_dim2 = np.array([1, 2, 3])
indices_dim3 = np.array([2, 3, 4])

result = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements:")
print(result)


Extracted elements:
[64 37 57]


Ques 34

In [76]:
def return_element(arr,x,y):
    return arr[(arr>x)& (arr<y)]
return_element(arr_2d,4,9)

array([5, 6, 7, 8])

Ques 35

In [77]:
import numpy as np

In [78]:
def extract_elements(x,y,z,w,arr):
    return arr[x:y,z:w]


In [79]:
s = np.random.randint(1,9,(5,5))
s

array([[2, 2, 6, 3, 3],
       [1, 2, 3, 2, 4],
       [8, 5, 7, 8, 8],
       [3, 8, 1, 5, 4],
       [1, 6, 5, 1, 8]], dtype=int32)

In [80]:
extract_elements(2,5,2,5,s)


array([[7, 8, 8],
       [1, 5, 4],
       [5, 1, 8]], dtype=int32)

Ques 36

In [81]:
arr = np.random.randint(1,9,(3,3))

In [82]:
arr

array([[7, 6, 4],
       [7, 5, 1],
       [7, 1, 5]], dtype=int32)

In [83]:
arr+5

array([[12, 11,  9],
       [12, 10,  6],
       [12,  6, 10]], dtype=int32)

Ques 37

In [84]:
arr1 = np.array([[2,3,4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

result = np.transpose(arr1) * arr2

print("Result:")
print(result)


Result:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


Ques 38

In [85]:
arr1 = np.array([[2, 3,4, 5]])
arr1_tp = np.transpose(arr1)
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])
result = arr1_tp + arr2

print("Result:")
print(result)


Result:
[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]
 [15 16 17]]


Ques 39

In [86]:
arr1 = np.random.randint(1,9,(3,1))
arr2 = np.random.randint(1,9,(1,3))
arr1,arr2

(array([[4],
        [5],
        [2]], dtype=int32),
 array([[3, 1, 8]], dtype=int32))

In [87]:
arr3 = arr1+arr2

In [88]:
arr3

array([[ 7,  5, 12],
       [ 8,  6, 13],
       [ 5,  3, 10]], dtype=int32)

Qunes 40

In [89]:
import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[2, 3],
                 [4, 5]])
result = np.transpose(arr1) @arr2

print("Result:")
print(result)


Result:
[[18 23]
 [24 31]
 [30 39]]


Ques 41

In [90]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [91]:
mean = np.mean(arr,axis=0)

In [92]:
mean


array([2.5, 3.5, 4.5])

Ques 42

In [93]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [94]:
maximum = np.max(arr,axis=1)

In [95]:
maximum

array([3, 6])

Ques 43

In [96]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [97]:
max_indices = np.argmax(arr, axis=0)


In [98]:
max_indices

array([1, 1, 1])

Ques 44

In [99]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [100]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [101]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
moving_sum = np.cumsum(arr, axis=1)
moving_sum

array([[ 1,  3,  6],
       [ 4,  9, 15]])

Ques 45

In [103]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
column_even = np.all(arr % 2 == 0, axis=0)
column_even

array([False, False, False])

Ques 46

In [104]:
original_array = np.array([1, 2, 3, 4, 5, 6])
arr1 = original_array.view().reshape(2,3)

In [105]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

Ques 47

In [106]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = input_matrix.flatten()
arr1

array([1, 2, 3, 4, 5, 6])

Ques 48

In [107]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
array3 = np.concatenate((array1,array2), axis=0)

In [108]:
array3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Qes 49

In [109]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1 = original_array.div

In [110]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
# Concatenate along axis 0 (vertically)
concatenated_arr = np.concatenate((arr1, arr2.T), axis=1)
print(concatenated_arr)

[[1 2 5]
 [3 4 6]]


In [111]:
arr2.T

array([[5],
       [6]])

Ques 49

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1 = split_array(original_array,num_splits =3,axis=1)

In [ ]:
arr1

In [113]:
arr4 = np.array([1, 2, 3])
inserted_arr = np.insert(arr4, 1, [8, 9])
print(inserted_arr)

[1 8 9 2 3]


In [114]:
deleted_arr = np.delete(arr4, [0,1])
print(deleted_arr)

[3]


Ques 50

In [115]:
original_array = np.array([1, 2, 3, 4, 5])
new_arr = np.insert(original_array,(2,4),(10,11))
new_arr

array([ 1,  2, 10,  3,  4, 11,  5])

In [116]:
new1_arr = np.delete(original_array,[1,3])
new1_arr

array([1, 3, 5])

In [118]:
# Qes 51

In [119]:
arr1 = np.random.randint(1,9,(3,3))
arr2 = np.random.randint(1,9,(3,3))
arr1,arr2

(array([[2, 5, 6],
        [1, 2, 6],
        [8, 2, 1]], dtype=int32),
 array([[4, 8, 8],
        [8, 1, 6],
        [7, 5, 5]], dtype=int32))

In [120]:
arr3 = arr1+arr2
arr3

array([[ 6, 13, 14],
       [ 9,  3, 12],
       [15,  7,  6]], dtype=int32)

Ques 52

In [121]:
arr1 = np.arange(10,1,-1)
arr2 = np.arange(1,10)
arr1,arr2
arr3 = arr1-arr2
arr3

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7])

Ques 53

In [122]:
arr1 = np.random.randint(1,5,(2,2))
arr2 = np.random.randint(1,5,(2,2))
arr1,arr2

(array([[3, 4],
        [4, 2]], dtype=int32),
 array([[4, 4],
        [3, 2]], dtype=int32))

In [123]:
arr3 = arr1*arr2
arr3

array([[12, 16],
       [12,  4]], dtype=int32)

Ques 54

In [124]:
arr1 = np.arange(2,11,2)
arr2 = np.random.randint(1,5,(5))

In [125]:
arr1,arr2

(array([ 2,  4,  6,  8, 10]), array([1, 2, 4, 4, 2], dtype=int32))

In [126]:
arr3 = arr1/arr2
arr3

array([2. , 2. , 1.5, 2. , 5. ])

Ques 55

In [127]:
arr1 = np.random.randint(1,5,5)

In [128]:
arr1

array([4, 3, 1, 4, 3], dtype=int32)

In [129]:
arr2 = np.flip(arr1)

In [130]:
arr2

array([3, 4, 1, 3, 4], dtype=int32)

In [131]:
arr3 = arr1**arr2
arr3

array([64, 81,  1, 64, 81], dtype=int32)

Ques 56

In [132]:
import numpy as np

def count_substring_occurrences(arr, substring):
    return np.char.count(arr, substring).sum()

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
target_substring = 'hello'
occurrences = count_substring_occurrences(arr, target_substring)
print(f"Occurrences of '{target_substring}': {occurrences}")


Occurrences of 'hello': 3


Ques 57

In [133]:
import numpy as np

def extract_uppercase_characters(arr):
    uppercase_chars = ' '.join([char for string in arr for char in string if char.isupper()])
    return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_result = extract_uppercase_characters(arr)
print("Uppercase characters:", uppercase_result)


Uppercase characters: H W O A I G P T


Ques 58

In [134]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
arr2 = np.char.replace(arr,'grape','mangos')
arr2

array(['apple', 'banana', 'mangos', 'pineapple'], dtype='<U9')

Ques 59

In [135]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
arr3 = np.core.defchararray.add(arr1, arr2)

C:\Users\piyus\AppData\Local\Temp\ipykernel_12712\1963408396.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.defchararray.
  arr3 = np.core.defchararray.add(arr1, arr2)


In [136]:
arr3

array(['HelloOpen', 'WorldAI'], dtype='<U9')

Ques 60

In [137]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
max = max(len(string) for string in arr)
max

9

Ques 61

In [138]:
arr = np.random.randint(1,1000,(100))
x = np.mean(arr)
x

np.float64(447.56)

In [139]:
np.median(arr)

np.float64(421.0)

In [140]:
np.var(arr)

np.float64(85903.86639999998)

In [141]:
np.std(arr)

np.float64(293.09361371411694)

Ques 62

In [142]:
arr = np.random.randint(1,100,50)

In [143]:
np.percentile(arr,25)

np.float64(19.25)

In [144]:
np.percentile(arr,75)

np.float64(64.75)

Ques63

In [145]:
import numpy as np

# Generate random data for two variables (arrays)
np.random.seed(42)  # For reproducibility
array1 = np.random.rand(100)  # Example data for variable 1
array2 = 2 * array1 + np.random.normal(0, 0.1, 100)  # Example data for variable 2 (with some noise)

# Compute the correlation coefficient
correlation_matrix = np.corrcoef(array1, array2)
correlation_coefficient = correlation_matrix[0, 1]

print(f"Correlation coefficient between the two arrays: {correlation_coefficient:.4f}")


Correlation coefficient between the two arrays: 0.9882


Ques 64

In [146]:
arr1 = np.random.randint(1,9,(2,2))


In [147]:
arr2 = np.random.randint(1,9,(2,2))
arr1,arr2

(array([[2, 5],
        [6, 1]], dtype=int32),
 array([[4, 7],
        [8, 1]], dtype=int32))

In [148]:
arr3 = np.dot(arr1,arr2)
arr3

array([[48, 19],
       [32, 43]], dtype=int32)

Ques 65

In [149]:
arr = np.random.randint(10,1000,50)

In [150]:
np.percentile(arr,10)

np.float64(103.00000000000001)

In [151]:
np.percentile(arr,50)

np.float64(422.0)

In [152]:
np.percentile(arr,90)

np.float64(842.3000000000001)

In [153]:
np.percentile(arr,25)

np.float64(192.5)

In [154]:
np.percentile(arr,75)

np.float64(688.25)

Ques 66

In [155]:
arr = np.random.randint(1,10,5)
arr

array([6, 7, 2, 2, 1], dtype=int32)

In [156]:
np.where(arr == 9)

(array([], dtype=int64),)

Ques 67

In [157]:
arr = np.random.randint(1,20,15)
arr

array([ 8,  1,  9, 11, 16,  7, 10,  3, 18, 13,  7,  4, 13,  1,  8],
      dtype=int32)

In [158]:
np.sort(arr)

array([ 1,  1,  3,  4,  7,  7,  8,  8,  9, 10, 11, 13, 13, 16, 18],
      dtype=int32)

Ques 68

In [159]:
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr>20]

array([25, 42, 30])

Ques 69

In [160]:
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3 == 0]

array([12, 15])

Ques 70

In [161]:
arr = np.array([10, 20, 30, 40, 50])
arr[(arr>=20)&(arr<=40)]

array([20, 30, 40])

Ques 71

In [162]:
arr = np.array([1, 2, 3])
arr.dtype.byteorder

'='

Ques 72

In [163]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)
arr

array([16777216, 33554432, 50331648], dtype=int32)

Ques 73

In [164]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.view(arr.dtype.newbyteorder())

array([16777216, 33554432, 50331648], dtype='>i4')

Ques 74

In [165]:
import numpy as np

arr = np.array([1, 2, 3])

system_endianness = np.dtype('int32').byteorder

swapped_arr = arr.view(arr.dtype.newbyteorder(system_endianness))

print("Original array:")
print(arr)
print("\nArray with swapped byte order (if needed):")
print(swapped_arr)


Original array:
[1 2 3]

Array with swapped byte order (if needed):
[1 2 3]


Ques 75

In [166]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

byte_order = arr.dtype.byteorder

if byte_order == '=':
    result = "No byte swapping necessary (native byte order)"
elif byte_order == '<':
    result = "Little-endian byte order (requires byte swapping)"
elif byte_order == '>':
    result = "Big-endian byte order (requires byte swapping)"
else:
    result = "Not applicable (e.g., for ASCII strings)"

result


'No byte swapping necessary (native byte order)'

Ques 76

In [167]:
import numpy as np

In [168]:
arr1 = np.random.randint(1,10,7)
arr1

array([3, 7, 2, 2, 7, 6, 3], dtype=int32)

In [169]:
arr2 = np.copy(arr1)
arr2

array([3, 7, 2, 2, 7, 6, 3], dtype=int32)

In [170]:
arr2[2] = 10

In [171]:
arr2

array([ 3,  7, 10,  2,  7,  6,  3], dtype=int32)

In [172]:
arr1

array([3, 7, 2, 2, 7, 6, 3], dtype=int32)

Ques 77

In [173]:
arr = np.random.randint(1,10,(3,3))
arr

array([[9, 6, 6],
       [1, 4, 6],
       [6, 5, 1]], dtype=int32)

In [174]:
arr2 = arr[1:3,1:3]

In [175]:
arr2

array([[4, 6],
       [5, 1]], dtype=int32)

In [176]:
arr2[1,1] = 5

In [177]:
arr2

array([[4, 6],
       [5, 5]], dtype=int32)

In [178]:
arr

array([[9, 6, 6],
       [1, 4, 6],
       [6, 5, 5]], dtype=int32)

Ques 78

In [179]:
array_a = np.arange(1,13)
array_a = array_a.view().reshape(4,3)
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [180]:
view_b = array_a[1:4,1:3]
view_b

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [181]:
view_b+5

array([[10, 11],
       [13, 14],
       [16, 17]])

In [182]:
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Ques 79

In [183]:
original_view = np.random.randint(1,9,(2,4))
original_view

array([[8, 5, 4, 4],
       [4, 5, 7, 4]], dtype=int32)

In [184]:
reshape_view = orignal_view.view().reshape(4,2)
reshape_view

NameError: name 'orignal_view' is not defined

In [185]:
reshape_view[2,1]=10

NameError: name 'reshape_view' is not defined

In [186]:
reshape_view

NameError: name 'reshape_view' is not defined

In [187]:
original_view


array([[8, 5, 4, 4],
       [4, 5, 7, 4]], dtype=int32)

Ques 80

In [188]:
data = np.random.randint(1,10,(3,4))
data

array([[6, 4, 3, 7],
       [8, 4, 2, 3],
       [1, 8, 3, 7]], dtype=int32)

In [189]:
data_copy = data[data>5]
data_copy

array([6, 7, 8, 8, 7], dtype=int32)

In [190]:
data_copy[5] = 20

IndexError: index 5 is out of bounds for axis 0 with size 5

In [191]:
data_copy

array([6, 7, 8, 8, 7], dtype=int32)

In [192]:
data

array([[6, 4, 3, 7],
       [8, 4, 2, 3],
       [1, 8, 3, 7]], dtype=int32)

Ques 81

In [193]:
arr1 = np.random.randint(1,11,(3,3))
arr2 = np.random.randint(1,11,(3,3))
arr1,arr2

(array([[10,  5, 10],
        [ 5,  7,  9],
        [ 5,  1, 10]], dtype=int32),
 array([[10,  1,  2],
        [ 6,  9,  8],
        [ 5,  1,  7]], dtype=int32))

In [194]:
arr1+arr2

array([[20,  6, 12],
       [11, 16, 17],
       [10,  2, 17]], dtype=int32)

In [195]:
arr1-arr2

array([[ 0,  4,  8],
       [-1, -2,  1],
       [ 0,  0,  3]], dtype=int32)

Ques 82

In [196]:
arr1 = np.random.randint(1,11,(3,2))
arr2 = np.random.randint(1,11,(2,4))
arr1,arr2

(array([[ 5,  6],
        [ 7,  3],
        [10,  3]], dtype=int32),
 array([[ 5,  6,  9,  5],
        [ 1,  4,  5, 10]], dtype=int32))

In [197]:
arr1@arr2

array([[ 31,  54,  75,  85],
       [ 38,  54,  78,  65],
       [ 53,  72, 105,  80]], dtype=int32)

Ques 83

In [198]:
arr = np.random.randint(1,11,(3,3))
arr,arr.T

(array([[10,  5,  7],
        [ 4,  1,  5],
        [ 7, 10, 10]], dtype=int32),
 array([[10,  4,  7],
        [ 5,  1, 10],
        [ 7,  5, 10]], dtype=int32))

Ques 84

In [199]:
arr = np.random.randint(1,11,(3,3))
arr

array([[ 6,  5,  4],
       [ 2,  4, 10],
       [10,  3, 10]], dtype=int32)

In [200]:
np.linalg.det(arr)

np.float64(324.00000000000017)

Ques 85

In [201]:
arr = np.random.randint(1,11,(3,3))
arr

array([[1, 8, 5],
       [4, 8, 7],
       [2, 1, 4]], dtype=int32)

In [202]:
np.linalg.inv(arr)

array([[-0.49019608,  0.52941176, -0.31372549],
       [ 0.03921569,  0.11764706, -0.25490196],
       [ 0.23529412, -0.29411765,  0.47058824]])